//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: dlg_setting.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _RATMOVE_WXMATHPLOT_DLG_SETTING_BASE_CLASSES_H
#define _RATMOVE_WXMATHPLOT_DLG_SETTING_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class DlgSysSettingBase : public wxDialog
{
protected:
    wxStaticText* m_staticText15;
    wxTextCtrl* m_textCtrlDataPath;
    wxButton* m_buttonBrowse;
    wxStdDialogButtonSizer* m_stdBtnSizer6;
    wxButton* m_buttonOK;
    wxButton* m_buttonCancel;

protected:
    virtual void OnButtonBrowse(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText15() { return m_staticText15; }
    wxTextCtrl* GetTextCtrlDataPath() { return m_textCtrlDataPath; }
    wxButton* GetButtonBrowse() { return m_buttonBrowse; }
    DlgSysSettingBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("System Setting"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(600,400), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgSysSettingBase();
};

#endif
