//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: play_video_clip.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _RATMOVE_WXMATHPLOT_PLAY_VIDEO_CLIP_BASE_CLASSES_H
#define _RATMOVE_WXMATHPLOT_PLAY_VIDEO_CLIP_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class DlgPlayVideoClipBase : public wxDialog
{
protected:
    wxPanel* m_panel4;
    wxPanel* m_panel18;
    wxPanel* m_panel6;
    wxButton* m_button10;
    wxButton* m_button12;
    wxButton* m_button14;
    wxButton* m_button16;
    wxButton* m_button20;

protected:

public:
    wxPanel* GetPanel4() { return m_panel4; }
    wxPanel* GetPanel18() { return m_panel18; }
    wxButton* GetButton10() { return m_button10; }
    wxButton* GetButton12() { return m_button12; }
    wxButton* GetButton14() { return m_button14; }
    wxButton* GetButton16() { return m_button16; }
    wxButton* GetButton20() { return m_button20; }
    wxPanel* GetPanel6() { return m_panel6; }
    DlgPlayVideoClipBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Play video clip"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,400), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~DlgPlayVideoClipBase();
};

#endif
