//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: play_video_clip.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _RATMOVE_WXMATHPLOT_PLAY_VIDEO_CLIP_BASE_CLASSES_H
#define _RATMOVE_WXMATHPLOT_PLAY_VIDEO_CLIP_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include "MyVideoPanel.h"
#include "MyPlotSegment.h"
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class DlgPlayVideoClipBase : public wxDialog
{
protected:
    MyVideoPanel* m_panelVideo;
    MyPlotSegment* m_panelProfile;
    wxPanel* m_panel6;
    wxButton* m_buttonPlay;
    wxButton* m_buttonPause;
    wxButton* m_buttonAccept;
    wxButton* m_buttonPartialAccept;
    wxButton* m_buttonReject;

protected:
    virtual void OnPaint(wxPaintEvent& event) { event.Skip(); }
    virtual void OnPlay(wxCommandEvent& event) { event.Skip(); }
    virtual void OnPause(wxCommandEvent& event) { event.Skip(); }

public:
    MyVideoPanel* GetPanelVideo() { return m_panelVideo; }
    MyPlotSegment* GetPanelProfile() { return m_panelProfile; }
    wxButton* GetButtonPlay() { return m_buttonPlay; }
    wxButton* GetButtonPause() { return m_buttonPause; }
    wxButton* GetButtonAccept() { return m_buttonAccept; }
    wxButton* GetButtonPartialAccept() { return m_buttonPartialAccept; }
    wxButton* GetButtonReject() { return m_buttonReject; }
    wxPanel* GetPanel6() { return m_panel6; }
    DlgPlayVideoClipBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Play video clip"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,600), long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
    virtual ~DlgPlayVideoClipBase();
};

#endif
