//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: play_video_clip.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "play_video_clip.h"


// Declare the bitmap loading function
extern void wxC4D83InitBitmapResources();

static bool bBitmapLoaded = false;


DlgPlayVideoClipBase::DlgPlayVideoClipBase(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC4D83InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* boxSizer2 = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizer2);
    
    m_panel4 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer2->Add(m_panel4, 2, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_panel18 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer2->Add(m_panel18, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_panel6 = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer2->Add(m_panel6, 0, wxALL, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer8 = new wxBoxSizer(wxHORIZONTAL);
    m_panel6->SetSizer(boxSizer8);
    
    m_button10 = new wxButton(m_panel6, wxID_ANY, _("Play"), wxDefaultPosition, wxDLG_UNIT(m_panel6, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 2904
    m_button10->SetBitmap(wxXmlResource::Get()->LoadBitmap(wxT("play")), wxTOP);
    m_button10->SetBitmapMargins(4,4);
    #endif
    
    boxSizer8->Add(m_button10, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button12 = new wxButton(m_panel6, wxID_ANY, _("Pause"), wxDefaultPosition, wxDLG_UNIT(m_panel6, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 2904
    m_button12->SetBitmap(wxXmlResource::Get()->LoadBitmap(wxT("pause")), wxTOP);
    m_button12->SetBitmapMargins(2,2);
    #endif
    
    boxSizer8->Add(m_button12, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button14 = new wxButton(m_panel6, wxID_ANY, _("My Button"), wxDefaultPosition, wxDLG_UNIT(m_panel6, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 2904
    m_button14->SetBitmap(wxXmlResource::Get()->LoadBitmap(wxT("like")), wxTOP);
    m_button14->SetBitmapMargins(2,2);
    #endif
    
    boxSizer8->Add(m_button14, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button16 = new wxButton(m_panel6, wxID_ANY, _("My Button"), wxDefaultPosition, wxDLG_UNIT(m_panel6, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 2904
    m_button16->SetBitmap(wxXmlResource::Get()->LoadBitmap(wxT("justice")), wxTOP);
    m_button16->SetBitmapMargins(2,2);
    #endif
    
    boxSizer8->Add(m_button16, 0, wxALL, WXC_FROM_DIP(5));
    
    m_button20 = new wxButton(m_panel6, wxID_ANY, _("My Button"), wxDefaultPosition, wxDLG_UNIT(m_panel6, wxSize(-1,-1)), 0);
    #if wxVERSION_NUMBER >= 2904
    m_button20->SetBitmap(wxXmlResource::Get()->LoadBitmap(wxT("dislike")), wxTOP);
    m_button20->SetBitmapMargins(2,2);
    #endif
    
    boxSizer8->Add(m_button20, 0, wxALL, WXC_FROM_DIP(5));
    
    SetName(wxT("DlgPlayVideoClipBase"));
    SetSize(500,400);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
}

DlgPlayVideoClipBase::~DlgPlayVideoClipBase()
{
}
