//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_nameFile = new wxMenu();
    m_menuBar->Append(m_nameFile, _("File"));
    
    m_menuItem7 = new wxMenuItem(m_nameFile, wxID_EXIT, _("Exit\tAlt-X"), _("Quit"), wxITEM_NORMAL);
    m_nameFile->Append(m_menuItem7);
    
    m_menuData = new wxMenu();
    m_menuBar->Append(m_menuData, _("Data"));
    
    m_menuItemDataAutoScroll = new wxMenuItem(m_menuData, wxID_DATA_AUTO_SCROLL, _("Auto Scrolling"), wxT(""), wxITEM_NORMAL);
    m_menuData->Append(m_menuItemDataAutoScroll);
    
    m_nameHelp = new wxMenu();
    m_menuBar->Append(m_nameHelp, _("Help"));
    
    m_menuItem9 = new wxMenuItem(m_nameHelp, wxID_ABOUT, _("About..."), wxT(""), wxITEM_NORMAL);
    m_nameHelp->Append(m_menuItem9);
    
    m_statusBar = new wxStatusBar(this, wxID_ANY, wxSTB_DEFAULT_STYLE);
    m_statusBar->SetFieldsCount(1);
    this->SetStatusBar(m_statusBar);
    
    m_auimgr19 = new wxAuiManager;
    m_auimgr19->SetManagedWindow( this );
    m_auimgr19->SetFlags( wxAUI_MGR_LIVE_RESIZE|wxAUI_MGR_TRANSPARENT_HINT|wxAUI_MGR_TRANSPARENT_DRAG|wxAUI_MGR_ALLOW_ACTIVE_PANE|wxAUI_MGR_ALLOW_FLOATING);
    m_auimgr19->GetArtProvider()->SetMetric(wxAUI_DOCKART_GRADIENT_TYPE, wxAUI_GRADIENT_NONE);
    
    m_auibar21 = new wxAuiToolBar(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxAUI_TB_PLAIN_BACKGROUND|wxAUI_TB_DEFAULT_STYLE);
    m_auibar21->SetToolBitmapSize(wxSize(32,32));
    
    m_auimgr19->AddPane(m_auibar21, wxAuiPaneInfo().Direction(wxAUI_DOCK_TOP).Layer(0).Row(0).Position(0).BestSize(42,42).MinSize(42,42).MaxSize(100,100).CaptionVisible(true).MaximizeButton(false).CloseButton(false).MinimizeButton(false).PinButton(false).ToolbarPane());
    
    m_auibar21->AddTool(wxID_DATA_AUTO_SCROLL, _("Auto Scrolling"), wxXmlResource::Get()->LoadBitmap(wxT("play")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_auibar21->AddTool(wxID_PAUSE, _("Pause"), wxXmlResource::Get()->LoadBitmap(wxT("pause")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    m_auibar21->Realize();
    
    m_panelPlot = new MyPlot(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    m_auimgr19->AddPane(m_panelPlot, wxAuiPaneInfo().Caption(_("Signal Plot")).Direction(wxAUI_DOCK_CENTER).Layer(0).Row(0).Position(0).BestSize(700,100).MinSize(700,100).MaxSize(700,100).CaptionVisible(true).MaximizeButton(false).CloseButton(false).MinimizeButton(false).PinButton(false));
    
    wxBoxSizer* topsizer = new wxBoxSizer(wxVERTICAL);
    m_panelPlot->SetSizer(topsizer);
    
    m_panelVideoView = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    m_auimgr19->AddPane(m_panelVideoView, wxAuiPaneInfo().Caption(_("Video Pane")).Direction(wxAUI_DOCK_BOTTOM).Layer(0).Row(0).Position(0).BestSize(50,100).MinSize(50,100).MaxSize(50,100).CaptionVisible(true).MaximizeButton(false).CloseButton(false).MinimizeButton(false).PinButton(false));
    
    wxBoxSizer* boxSizer67 = new wxBoxSizer(wxVERTICAL);
    m_panelVideoView->SetSizer(boxSizer67);
    
    m_panel69 = new wxPanel(m_panelVideoView, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelVideoView, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer67->Add(m_panel69, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer79 = new wxBoxSizer(wxHORIZONTAL);
    m_panel69->SetSizer(boxSizer79);
    
    m_panelVideo = new MyVideoPanel(m_panel69, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panel69, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer79->Add(m_panelVideo, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_panel83 = new wxPanel(m_panel69, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panel69, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer79->Add(m_panel83, 0, wxALL, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer85 = new wxBoxSizer(wxVERTICAL);
    m_panel83->SetSizer(boxSizer85);
    
    m_buttonAccept = new wxButton(m_panel83, wxID_ANY, _("Accept"), wxDefaultPosition, wxDLG_UNIT(m_panel83, wxSize(-1,-1)), 0);
    m_buttonAccept->SetBackgroundColour(wxColour(wxT("rgb(128,255,0)")));
    
    boxSizer85->Add(m_buttonAccept, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonPartialAccept = new wxButton(m_panel83, wxID_ANY, _("Partial Accept"), wxDefaultPosition, wxDLG_UNIT(m_panel83, wxSize(-1,-1)), 0);
    m_buttonPartialAccept->SetBackgroundColour(wxColour(wxT("rgb(255,255,0)")));
    
    boxSizer85->Add(m_buttonPartialAccept, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonReject = new wxButton(m_panel83, wxID_ANY, _("Reject"), wxDefaultPosition, wxDLG_UNIT(m_panel83, wxSize(-1,-1)), 0);
    m_buttonReject->SetBackgroundColour(wxColour(wxT("rgb(255,0,0)")));
    
    boxSizer85->Add(m_buttonReject, 0, wxALL, WXC_FROM_DIP(5));
    
    m_panel71 = new wxPanel(m_panelVideoView, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(m_panelVideoView, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    boxSizer67->Add(m_panel71, 0, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    wxBoxSizer* boxSizer73 = new wxBoxSizer(wxHORIZONTAL);
    m_panel71->SetSizer(boxSizer73);
    
    m_buttonReplay = new wxButton(m_panel71, wxID_ANY, _("Replay"), wxDefaultPosition, wxDLG_UNIT(m_panel71, wxSize(-1,-1)), 0);
    
    boxSizer73->Add(m_buttonReplay, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonPlay = new wxButton(m_panel71, wxID_ANY, _("Play"), wxDefaultPosition, wxDLG_UNIT(m_panel71, wxSize(-1,-1)), 0);
    
    boxSizer73->Add(m_buttonPlay, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonPause = new wxButton(m_panel71, wxID_ANY, _("Pause"), wxDefaultPosition, wxDLG_UNIT(m_panel71, wxSize(-1,-1)), 0);
    
    boxSizer73->Add(m_buttonPause, 0, wxALL, WXC_FROM_DIP(5));
    
    m_buttonStop = new wxButton(m_panel71, wxID_ANY, _("Stop"), wxDefaultPosition, wxDLG_UNIT(m_panel71, wxSize(-1,-1)), 0);
    
    boxSizer73->Add(m_buttonStop, 0, wxALL, WXC_FROM_DIP(5));
    
    m_panelMsg = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDLG_UNIT(this, wxSize(-1,-1)), wxTAB_TRAVERSAL);
    
    m_auimgr19->AddPane(m_panelMsg, wxAuiPaneInfo().Name(wxT("MsgPane")).Caption(_("Message Pane")).Direction(wxAUI_DOCK_BOTTOM).Layer(0).Row(0).Position(1).BestSize(550,280).MinSize(550,280).MaxSize(550,280).CaptionVisible(true).MaximizeButton(false).CloseButton(false).MinimizeButton(false).PinButton(false));
    m_auimgr19->Update();
    
    wxBoxSizer* boxSizer29 = new wxBoxSizer(wxVERTICAL);
    m_panelMsg->SetSizer(boxSizer29);
    
    m_textCtrlMsg = new wxTextCtrl(m_panelMsg, wxID_ANY, wxT(""), wxDefaultPosition, wxDLG_UNIT(m_panelMsg, wxSize(-1,-1)), wxTE_WORDWRAP|wxTE_RICH2|wxTE_RICH|wxTE_MULTILINE);
    
    boxSizer29->Add(m_textCtrlMsg, 1, wxALL|wxEXPAND, WXC_FROM_DIP(5));
    
    m_timerScroll = new wxTimer;
    
    SetName(wxT("MainFrameBaseClass"));
    SetSize(950,650);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(MainFrameBaseClass::OnClose), NULL, this);
    this->Connect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Connect(m_menuItemDataAutoScroll->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnDataAutoScrolling), NULL, this);
    this->Connect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Connect(wxID_DATA_AUTO_SCROLL, wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnUpdateUIAutoScroll), NULL, this);
    this->Connect(wxID_PAUSE, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnScrollPause), NULL, this);
    m_panelVideo->Connect(wxEVT_PAINT, wxPaintEventHandler(MainFrameBaseClass::OnPaint), NULL, this);
    m_buttonAccept->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnAccept), NULL, this);
    m_buttonPartialAccept->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnPartialAccept), NULL, this);
    m_buttonReject->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnReject), NULL, this);
    m_buttonReplay->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoReplay), NULL, this);
    m_buttonPlay->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoPlay), NULL, this);
    m_buttonPause->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoPause), NULL, this);
    m_buttonStop->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoStop), NULL, this);
    m_timerScroll->Connect(wxEVT_TIMER, wxTimerEventHandler(MainFrameBaseClass::OnScrollbarTimer), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(wxEVT_CLOSE_WINDOW, wxCloseEventHandler(MainFrameBaseClass::OnClose), NULL, this);
    this->Disconnect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Disconnect(m_menuItemDataAutoScroll->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnDataAutoScrolling), NULL, this);
    this->Disconnect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Disconnect(wxID_DATA_AUTO_SCROLL, wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnUpdateUIAutoScroll), NULL, this);
    this->Disconnect(wxID_PAUSE, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnScrollPause), NULL, this);
    m_panelVideo->Disconnect(wxEVT_PAINT, wxPaintEventHandler(MainFrameBaseClass::OnPaint), NULL, this);
    m_buttonAccept->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnAccept), NULL, this);
    m_buttonPartialAccept->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnPartialAccept), NULL, this);
    m_buttonReject->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnReject), NULL, this);
    m_buttonReplay->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoReplay), NULL, this);
    m_buttonPlay->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoPlay), NULL, this);
    m_buttonPause->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoPause), NULL, this);
    m_buttonStop->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnVideoStop), NULL, this);
    m_timerScroll->Disconnect(wxEVT_TIMER, wxTimerEventHandler(MainFrameBaseClass::OnScrollbarTimer), NULL, this);
    
    m_auimgr19->UnInit();
    delete m_auimgr19;

    m_timerScroll->Stop();
    wxDELETE( m_timerScroll );

}
