//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _RATMOVE_WXMATHPLOT_WXCRAFTER_BASE_CLASSES_H
#define _RATMOVE_WXMATHPLOT_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/menu.h>
#include <wx/statusbr.h>
#include <wx/aui/framemanager.h>
#include <wx/aui/dockart.h>
#include <wx/pen.h>
#include <wx/aui/auibar.h>
#include <map>
#include <wx/toolbar.h>
#include <wx/panel.h>
#include "MyPlot.h"
#include <wx/tglbtn.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#include <wx/timer.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBaseClass : public wxFrame
{
public:
    enum {
        wxID_DATA_AUTO_SCROLL = 10001,
        wxID_PAUSE = 10002,
        wxID_REWIND = 10003,
    };
protected:
    wxMenuBar* m_menuBar;
    wxMenu* m_nameFile;
    wxMenuItem* m_menuItem7;
    wxMenu* m_menuData;
    wxMenuItem* m_menuItemDataAutoScroll;
    wxMenu* m_nameHelp;
    wxMenuItem* m_menuItem9;
    wxStatusBar* m_statusBar;
    wxAuiManager* m_auimgr19;
    wxAuiToolBar* m_auibar21;
    MyPlot* m_panelPlot;
    wxPanel* m_panelTools;
    wxToggleButton* m_toggleButtonCoord;
    wxPanel* m_panelPara;
    wxPanel* m_panelMsg;
    wxTextCtrl* m_textCtrlMsg;
    wxTimer* m_timerScroll;

protected:
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnDataAutoScrolling(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }
    virtual void OnScrollPause(wxCommandEvent& event) { event.Skip(); }
    virtual void OnScrollPrevious(wxCommandEvent& event) { event.Skip(); }
    virtual void OnScrollNext(wxCommandEvent& event) { event.Skip(); }
    virtual void OnToggleShowCoord(wxCommandEvent& event) { event.Skip(); }
    virtual void OnScrollbarTimer(wxTimerEvent& event) { event.Skip(); }

public:
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxStatusBar* GetStatusBar() { return m_statusBar; }
    wxAuiToolBar* GetAuibar21() { return m_auibar21; }
    MyPlot* GetPanelPlot() { return m_panelPlot; }
    wxToggleButton* GetToggleButtonCoord() { return m_toggleButtonCoord; }
    wxPanel* GetPanelTools() { return m_panelTools; }
    wxPanel* GetPanelPara() { return m_panelPara; }
    wxTextCtrl* GetTextCtrlMsg() { return m_textCtrlMsg; }
    wxPanel* GetPanelMsg() { return m_panelMsg; }
    wxAuiManager* GetAuimgr19() { return m_auimgr19; }
    wxTimer* GetTimerScroll() { return m_timerScroll; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(950,650), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
